spring.application.name=tasks

# --- DATASOURCE ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/shop}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# --- LIQUIBASE ---
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# --- SERVER ---
server.port=8080

# --- LOG ---
logging.pattern.level=%5p [traceId=%X{traceId}]
logging.level.org.springframework.web=DEBUG
server.error.include-message=always
include-binding-errors: always